[package]
name = "siumai-provider-deepseek"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "DeepSeek provider implementation for siumai"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/siumai-provider-deepseek"
readme = "../README.md"
keywords = ["llm", "ai", "deepseek"]
categories = ["api-bindings"]

[lib]
doctest = false

[dependencies]
siumai-core = { workspace = true, default-features = false }
siumai-anthropic-compatible = { workspace = true, default-features = false }
siumai-openai-compatible = { version = "0.11.0-beta.10", path = "../siumai-openai-compatible", default-features = false }
siumai-protocol-anthropic = { workspace = true, default-features = false }
siumai-protocol-openai = { version = "0.11.0-beta.10", path = "../siumai-protocol-openai", default-features = false, features = ["openai-responses"] }
siumai-transport = { workspace = true, default-features = false }

async-trait.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[features]
default = []

[dev-dependencies]
futures-util.workspace = true
tokio.workspace = true
wiremock.workspace = true
