//! Core Error Types
//!
//! This module defines the core error types used throughout the LLM library:
//! - `LlmError`: The main error enum
//! - `Result<T>`: Type alias for Result<T, LlmError>

use thiserror::Error;

/// The primary error type for the LLM library.
#[derive(Error, Debug, Clone)]
pub enum LlmError {
    /// HTTP request error
    #[error("HTTP request failed: {0}")]
    HttpError(String),

    /// JSON serialization/deserialization error
    #[error("JSON error: {0}")]
    JsonError(String),

    /// Response parsing error
    #[error("Parse error: {0}")]
    ParseError(String),

    /// Structured object generation completed but no valid object could be parsed or validated.
    #[error("{message}")]
    NoObjectGenerated {
        /// Error message.
        message: String,
        /// Raw text generated by the model when available.
        text: Option<String>,
        /// Best-effort response metadata.
        response: Option<Box<crate::types::GenerateObjectResponseMetadata>>,
        /// Best-effort usage metadata.
        usage: Option<Box<crate::types::LanguageModelUsage>>,
        /// Finish reason from the model response.
        finish_reason: Option<crate::types::FinishReason>,
        /// Underlying parse or validation error.
        cause: Option<Box<LlmError>>,
    },

    /// Video generation completed successfully at the task layer but produced no final video.
    #[error("No video generated.")]
    NoVideoGenerated {
        /// Best-effort final response metadata for each generation call.
        responses: Vec<crate::types::HttpResponseInfo>,
    },

    /// Image generation completed successfully but produced no final image.
    #[error("No image generated.")]
    NoImageGenerated {
        /// Best-effort final response metadata for each generation call.
        responses: Vec<crate::types::HttpResponseInfo>,
    },

    /// Speech synthesis completed successfully but produced no final audio bytes.
    #[error("No speech audio generated.")]
    NoSpeechGenerated {
        /// Best-effort final response metadata for each generation call.
        responses: Vec<crate::types::HttpResponseInfo>,
    },

    /// Transcription completed successfully but produced no final transcript text.
    #[error("No transcript generated.")]
    NoTranscriptGenerated {
        /// Best-effort final response metadata for each generation call.
        responses: Vec<crate::types::HttpResponseInfo>,
    },

    /// Invalid input error
    #[error("Invalid input: {0}")]
    InvalidInput(String),

    /// IO error
    #[error("IO error: {0}")]
    IoError(String),

    /// Not found error
    #[error("Not found: {0}")]
    NotFound(String),

    /// Missing API key
    #[error("Missing API key: {0}")]
    MissingApiKey(String),

    /// Invalid parameter
    #[error("Invalid parameter: {0}")]
    InvalidParameter(String),

    /// API error response
    #[error("API error: {code} - {message}")]
    ApiError {
        code: u16,
        message: String,
        details: Option<serde_json::Value>,
    },

    /// Authentication error
    #[error("Authentication failed: {0}")]
    AuthenticationError(String),

    /// Rate limit error
    #[error("Rate limit exceeded: {0}")]
    RateLimitError(String),

    /// Quota exceeded error
    #[error("Quota exceeded: {0}")]
    QuotaExceededError(String),

    /// Model not supported error
    #[error("Model not supported: {0}")]
    ModelNotSupported(String),

    /// Stream processing error
    #[error("Stream error: {0}")]
    StreamError(String),

    /// Timeout error
    #[error("Request timeout: {0}")]
    TimeoutError(String),

    /// Network connection error
    #[error("Connection error: {0}")]
    ConnectionError(String),

    /// Provider-specific error
    #[error("Provider error ({provider}): {message}")]
    ProviderError {
        provider: String,
        message: String,
        error_code: Option<String>,
    },

    /// Configuration error
    #[error("Configuration error: {0}")]
    ConfigurationError(String),

    /// Internal error
    #[error("Internal error: {0}")]
    InternalError(String),

    /// Unsupported operation
    #[error("Unsupported operation: {0}")]
    UnsupportedOperation(String),

    /// Processing error
    #[error("Processing error: {0}")]
    ProcessingError(String),

    /// Tool call error
    #[error("Tool call error: {0}")]
    ToolCallError(String),

    /// Tool validation error
    #[error("Tool validation error: {0}")]
    ToolValidationError(String),

    /// Unsupported tool type
    #[error("Unsupported tool type: {0}")]
    UnsupportedToolType(String),

    /// Context-aware error with additional metadata
    #[error("Error in {context}: {message}")]
    ContextualError {
        context: String,
        message: String,
        source_error: Option<Box<LlmError>>,
        metadata: std::collections::HashMap<String, String>,
    },

    /// Other errors
    #[error("Other error: {0}")]
    Other(String),
}

impl LlmError {
    /// Creates a new API error.
    pub fn api_error(code: u16, message: impl Into<String>) -> Self {
        Self::ApiError {
            code,
            message: message.into(),
            details: None,
        }
    }

    /// Creates a new API error with details.
    pub fn api_error_with_details(
        code: u16,
        message: impl Into<String>,
        details: serde_json::Value,
    ) -> Self {
        Self::ApiError {
            code,
            message: message.into(),
            details: Some(details),
        }
    }

    /// Creates a new provider error.
    pub fn provider_error(provider: impl Into<String>, message: impl Into<String>) -> Self {
        Self::ProviderError {
            provider: provider.into(),
            message: message.into(),
            error_code: None,
        }
    }

    /// Creates a new provider error with an error code.
    pub fn provider_error_with_code(
        provider: impl Into<String>,
        message: impl Into<String>,
        error_code: impl Into<String>,
    ) -> Self {
        Self::ProviderError {
            provider: provider.into(),
            message: message.into(),
            error_code: Some(error_code.into()),
        }
    }

    /// Creates a new contextual error with metadata.
    pub fn contextual_error(context: impl Into<String>, message: impl Into<String>) -> Self {
        Self::ContextualError {
            context: context.into(),
            message: message.into(),
            source_error: None,
            metadata: std::collections::HashMap::new(),
        }
    }

    /// Creates a contextual error with a source error.
    pub fn contextual_error_with_source(
        context: impl Into<String>,
        message: impl Into<String>,
        source: LlmError,
    ) -> Self {
        Self::ContextualError {
            context: context.into(),
            message: message.into(),
            source_error: Some(Box::new(source)),
            metadata: std::collections::HashMap::new(),
        }
    }

    /// Creates a contextual error with metadata.
    pub fn contextual_error_with_metadata(
        context: impl Into<String>,
        message: impl Into<String>,
        metadata: std::collections::HashMap<String, String>,
    ) -> Self {
        Self::ContextualError {
            context: context.into(),
            message: message.into(),
            source_error: None,
            metadata,
        }
    }
}

/// Result type alias.
pub type Result<T> = std::result::Result<T, LlmError>;
