[package]
name = "siumai-provider-google-vertex"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "Anthropic Messages provider on Google Vertex AI for siumai"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/siumai-provider-google-vertex"
readme = "../README.md"
keywords = ["llm", "ai", "google", "vertex"]
categories = ["api-bindings"]

[lib]
doctest = false

[dependencies]
siumai-core = { workspace = true, default-features = false }
siumai-protocol-anthropic = { version = "0.11.0-beta.11", path = "../siumai-protocol-anthropic", default-features = false }
siumai-anthropic-compatible = { workspace = true }
siumai-transport = { workspace = true, default-features = false }

async-trait.workspace = true
http.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
futures-util.workspace = true
chrono.workspace = true
thiserror.workspace = true
secrecy.workspace = true

[features]
default = []

[dev-dependencies]
wiremock.workspace = true
